author:
  email: wsgwhym@163.com
  name: Kui Xue
baseurl: https://xuekui.site/
copyright: © Kui Xue
languagecode: en-us
enablerobotstxt: true
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: vs
menu:
  main:
  - identifier: home
    name: Home
    weight: 10
    url: /
  - identifier: about
    name: About
    weight: 20
    url: /about/
  - identifier: blog
    name: Blog
    weight: 30
    url: /blog/
  - identifier: articles
    name: Articles
    weight: 40
    url: /articles/
  - identifier: projects
    name: Projects
    weight: 50
    url: /projects/
  - identifier: categories
    name: Categories
    weight: 60
    url: /categories/
  - identifier: tags
    name: Tags
    weight: 70
    url: /tags/
paginate: 50
permalinks:
  blog: /blog/:year/:month/:day/:title/
social:
  envelope: mailto:example@example.com
  github: https://github.com/example
  twitter: https://twitter.com/example
theme: "paige"
timezone: America/Los_Angeles
title: Kui Xue丨薛奎
titlecasestyle: Go
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
