author:
  email: wsgwhym@163.com
  name: Kui Xue
baseurl: https://xuekui.site/
copyright: 
  © Kui Xue. 
  Powered by the [paige theme](https://github.com/willfaught/paige)
  for [Hugo](https://gohugo.io/).
languagecode: en-us
enablerobotstxt: true
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    codeFences: true
    hl_Lines: ""
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
menu:
  main:
  - identifier: home
    name: Home
    weight: 10
    url: /
  - identifier: about
    name: About
    weight: 20
    url: /about/
  - identifier: blog
    name: Blog
    weight: 30
    url: /blog/
  - identifier: projects
    name: Projects
    weight: 50
    url: /projects/
  - identifier: categories
    name: Categories
    weight: 60
    url: /categories/
  - identifier: tags
    name: Tags
    weight: 70
    url: /tags/
paginate: 30
permalinks:
  blog: /blog/:year/:month/:day/:title/
social:
  envelope: wsgwhym@163.com
  github: https://github.com/xuekui9
  twitter: https://twitter.com/xuekui9
theme: "paige"
timezone: Asia/Shanghai
title: Kui Xue丨薛奎
titlecasestyle: Go
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
  