params:
  author: 
    email: wsgwhym@163.com
    name: Kui Xue
    baseurl: https://xuekui.site
  social:
    envelope: mailto:wsgwhym@163.com
    github: https://github.com/xuekui9
    twitter: https://twitter.com/xuekui9
copyright: 
  © Kui Xue. 
  Powered by the [paige theme](https://github.com/willfaught/paige)
  for [Hugo](https://gohugo.io/).
languagecode: en-us
enablerobotstxt: true
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    codeFences: true
    hl_Lines: ""
    lineNumbersInTable: true
    noClasses: true
    style: vs
    tabWidth: 4
menu:
  main:
  - identifier: home
    name: Home
    weight: 10
    url: /
  - identifier: about
    name: Info
    weight: 20
    url: /about/
  - identifier: blog
    name: Blog
    weight: 30
    url: /blog/
  - identifier: myphoto
    name: Photos
    weight: 40
    url: /myphoto/
  - identifier: projects
    name: Projects
    weight: 50
    url: /projects/
  - identifier: categories
    name: Categories
    weight: 60
    url: /categories/
  - identifier: tags
    name: Tags
    weight: 70
    url: /tags/
pagination:
  pagerSize: 30
permalinks:
  blog: /blog/:year/:month/:slug/

theme: paige
timezone: Asia/Shanghai
title: Kui Xue丨薛奎
enableEmoji: true
titlecasestyle: Go
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$


