---
title: 'MBC determination '
author: ''
date: '2023-04-01'
slug: mbc
categories: []
tags: [实验]
description: '郭李琦，薛奎，孔童瑶'
keywords: []
link: ''

output:
  blogdown::html_page:
    toc: true
    number_sections: true



---



# MBC测定


## 物品

称量

- 千分天平、烧杯、手撕美工纸、尖底离心管（50mL）及试管架、记号笔、丁腈手套、药匙、滤纸、称量纸、记录本、2B铅笔、削笔刀


熏蒸

- 真空干燥箱、气泵、口罩、丁腈手套、氯仿、沸石、NaOH、药匙、100mL烧杯、玻璃棒、封口膜、黑色袋子



浸提、过滤与离心

- 天平、药匙、K~2~SO~4~、移液枪或自动进样器、1L烧杯、1L容量瓶、磁力搅拌器或玻璃棒
- 新的50mL尖底离心管、60mL尿杯、无磷滤纸、记号笔
- 涡旋仪、摇床、离心机





## 称样

鲜土储存在4°C。处理组称取10g鲜土到50mL小烧杯中，对照组称取10g鲜土到离心管，盖上盖。

熏蒸的样品须**放在烧杯**中，不能放入离心管内。氯仿或真空环境会腐蚀离心管；

往烧杯上标号时，须贴上美工纸并用**铅笔标号**。氯仿会腐蚀记号笔印迹。

称样10个样品，约20分钟


## 放样

干燥箱有3层。将称好的土样放入干燥箱，每层的外缘预留出位置，分别放氯仿、NaOH溶液和水。

- NaOH。配100mL、2mol/L的NaOH溶液。即称取8g NaOH到**烧杯**中，加水至100mL。将配好的NaOH溶液分两份于两个50mL烧杯中，可以先用封口膜封上，减少与空气CO~2~的反应。放置在干燥箱下层。
- 水。拿1个50mL烧杯，加入水，放入干燥箱。
- 氯仿。先打开通风橱风机；准备两个100mL烧杯，底部先铺一层沸石；两烧杯中各加入40-50mL氯仿，放在干燥箱外缘预留位置，关上箱门密闭。


在真空干燥箱中进行氯仿熏蒸时，氯仿挥发及微生物呼吸的CO~2~会影响干燥箱中的气压，加NaOH是为了吸收掉CO~2~，低气压下使得氯仿更易挥发。

## 抽气


干燥箱抽气阀初始为关闭状态。

将干燥箱的导气管连接抽气泵，（抽气泵尽可能往通风橱里面放）；此时让它抽气，等待箱内气压降低即可。待氯仿开始连续沸腾，压力表指针处在黄色区域，约0.07MPa；维持氯仿沸腾两分钟。



先关抽气阀，再关气泵。让通风橱风机再工作5min，保证排尽残留的氯仿，最后关闭风机。





## 熏蒸



在黑暗条件下熏蒸24h；需要给处理组、对照组蒙上黑袋。

对照组的离心管放置在避光环境。离心管如果放在真空环境中，可能会化掉。



隔2小时查看压力表指针是否大幅转动。如有大幅转动，证明气密性不好，须重新检查干燥箱气密性。即：打开风机，重新关紧干燥箱门。重新抽气进行熏蒸，并重新计时。



熏蒸结束后，正常压力表指针会在黄色与绿色区域的交界处

- 先打开风机，拿出氯仿的同时将其回收至原来的氯仿瓶内，尽量不要把沸石倒进去；沸石倒入密封袋并封口；
- 将NaOH溶液（反应后部分变成Na~2~CO~3~）倒掉；
- 取出烧杯，放置在干燥箱上方，风机继续工作一个多小时排除样品中的残留氯仿，因氯仿中含碳；





## 浸提与离心



配制浸提剂0.5mol/L K~2~SO~4~溶液。87.1g K~2~SO~4~可得1L浸提剂。记得配置时不要直接往烧杯加1L水，因为需要润洗烧杯，最后定容到1L。K~2~SO~4~难溶解，可以用磁力搅拌器。




将熏蒸样品转移至离心管，每个离心管中共计准确加入40mL浸提剂。**一定在离心管上做好标记：处理还是对照。**

如果烧杯中有残留土样，配合移液枪加入浸提剂，将残留土样冲洗至离心管内。


至此，处理与对照（熏蒸与未熏蒸）的样品都在离心管内，并加入了K~2~SO~4~。


将离心管放入涡旋仪，3min；摇床振荡，220rmp，0.5h。最后放入离心机，4000rmp，10min。离心前注意检查配平、检查盖是否盖好。



## 过滤与测定

使用定量滤纸对浸提液进行过滤，收集在60mL的尿杯中。叠滤纸时佩戴手套；**尿杯也要做好标记：处理还是对照。**过滤后离心管及管内的土样可以丢掉。


过滤到离心管还是尿杯中？尿杯口径大，过滤速度快很多。



测定。若一周内可上机测，储存在4度环境；否则保存在-20度。


- 使用CN分析仪液体模块测定DOC/N，MBC/N。记录原始浓度的数据；
- 由于0.5mol/L K~2~SO~4~浓度偏高，上机会堵塞仪器。须用去离子水稀释浸提液5倍。移液枪取1mL浸提液到15mL离心管，稀释到5mL；
- 使用仪器自带针管取300μL，**必须缓缓**打入进样口。


测一个3min。可以一个人稀释浸提液，一个人打样品。