---
title: Gas chromatography 7890A
author: Package Build
date: '2024-06-03'
slug: gc7890
categories: []
tags:
  - 实验
description: ''
keywords: []
link: ''

output:
  blogdown::html_page:
    toc: true
    number_sections: true
    
---

# 气相色谱

## 耗材

载气

- N2，用于CO2及CH4测定，200元/瓶；
- 氩/甲烷，用于N2O测定，1k-2k间；

标气

- CO2/CH4/N2O混合标气，3k每瓶，可用1年多；


## 气体柜

气体柜中包括气瓶阀，进气阀，排气阀。两个钢瓶分别为N2、氩甲烷。

打开钢瓶总阀门前，为避免钢瓶内气压对进气阀造成冲击，应先打开进气阀（逆时针拧到底），再打开气瓶阀（拧两三下）。

钢瓶满压时指针约15，不到1格时更换气瓶。流速阀不用动，已调好。

## 氢气发生器及气泵

打开氢气发生器身后开关，打开气泵开关。

- 氢气发生器的水位，缺水时加入去离子水；
- 及时更换氢气发生器后部及与气泵连接的的干燥剂；

## 仪器主机

首先打开7890总开关，然后：

Yes或No按键调整开关状态。

1. Oven。柱箱（开，温度会逐渐升至55）；
1. Front Det，前检测器用于测CH4/CO2。温度（开，预热升至250）；H2（开，45），空气流量（开，升至400），尾吹气（关）；火焰（开），一般会自动开，如果闪烁先关闭再手动打开，如果不闪烁手动打开；
1. Back Det，后检测器用于测N2O。温度（开，330）；尾吹气（开）；
1. Aux Temp，辅助温度。温度（一定开，375）；



## 电脑

经常打开，不用关机。桌面软件为“仪器1 联机”。如果电脑与7890连接后，7890箱体上Remote指示灯为橙色。

## 测气

调整7890至Time界面。（按照需求）依次往不同进气口，分别注射6mL气体（范围5-10mL）。然后按7890箱体上的“Start”，Time界面即开始倒计时5分钟。


### 标气

标气气瓶要格外注意，确保气瓶总阀处于关闭状态，将注射器与三通阀连接。首先要沿Decrease方向转动减压阀（关闭），再拧开气瓶总阀，这个时候一点一点Increase减压阀，慢慢地会感觉到有阻尼感，再慢慢一点一点Increase，标气会进入注射器。然后反方向拧动关闭减压阀。

通常前两管标气中混有空气不准，打到空气中丢掉。

重新再采集一定体积的标气，Decrease关闭减压阀，关闭气瓶阀。

一般先打3次标气，3次结果CV要小于0.01。通过后，再开始正式测气。

### 结果

不论标气还是样品气，均记录结果中的峰面积用于计算。

- CH4。（前部）时间1.1左右的数据行所对应的峰面积。
- CO2。（前部）时间3.8左右的数据行所对应的峰面积。
- N2O。（后部）时间xxx左右的数据行所对应的峰面积。

# 关机

关掉Oven，Front Det，Back Det及Aux Temp中之间打开的选项。因为Aux Temp中温度降的比较慢，一般降至50度以下时，就可以关闭气相色谱。

关闭氢气发生器。关闭钢瓶阀以及进气阀。电脑不关。



