---
title: "R book in NEFU"
author: "Kui Xue"
date: "2022-08-01"
output:
  prettydoc::html_pretty:
    theme: hpstr
    highlight: github
    number_sections: yes #是否自动按节编号
    toc: yes # table of content
   
 
---

```{r include=FALSE}
library(tidyverse)
knitr::opts_chunk$set(warning=FALSE,message=FALSE,collapse = TRUE, fig.align="center",fig.width = 8)
```

<!-- include= FALSE, hide code chunk above. -->




```{r pressure, include=FALSE}
df= tibble::tribble(
  ~Name,                          ~Author,                ~Pub_Date,  
   "统计模拟及其R实现",                    "肖枝洪",                  "2010-04", 
   "时间序列分析及应用:R语言",                "Jonathan D. Cryer",    "2011-01", 
   "R语言数据操作",                      "菲尔·斯佩克特",              "2011-07", 
   "环境与生态统计:R语言的应用",               "钱松",                   "2011-07", 
   "R语言初学者指南",                     "阿兰·F·祖尔",              "2011-09", 
   "R语言经典实例",                      "Paul Teetor",          "2013-05", 
   "R语言编程艺术",                      "Norman Matloff",       "2013-05", 
   "数据挖掘与R语言",                     "Luis Torgo",           "2013-07", 
   "R语言与Bioconductor生物信息学应用",      "高山",                   "2014-01", 
   "R语言与网站分析",                     "李明",                   "2014-04", 
   "R数据可视化手册",                     "Winston Chang",        "2014-05", 
   "数据挖掘:R语言实战",                   "黄文",                   "2014-06", 
   "R语言统计入门",                      "Peter Dalgaard",       "2014-06", 
   "学习R",                          "Richard Cotton",       "2014-06", 
   "R语言核心技术手册",                    "Joseph Adler",         "2014-07", 
   "数据分析:R语言实战",                   "李诗羽",                  "2014-08", 
   "R的极客理想,工具篇",                   "张丹",                   "2014-08", 
   "R语言与数据挖掘最佳实践和经典案例",            "Yanchang Zhao",        "2014-09", 
   "R语言实用教程",                      "薛毅",                   "2014-10", 
   "R语言的科学编程与仿真",                  "欧文·琼斯",                "2014-12", 
   "非参数统计:基于R语言案例分析",              "柳向东",                  "2015-02", 
   "R数据分析:方法与案例详解",                "方匡南",                  "2015-02", 
   "R软件教程与统计分析:入门到精通",             "麦考斯",                  "2015-04", 
   "R软件入门与基础",                     "张志杰",                  "2015-04", 
   "R语言轻松入门与提高",                   "Andrie de Vries",      "2015-05", 
   "统计学习导论:基于R应用",                 "加雷斯·詹姆斯",              "2015-05", 
   "数据科学中的R语言",                    "李航",                   "2015-07", 
   "R的极客理想,高级开发篇",                 "张丹",                   "2015-07", 
   "游戏数据分析的艺术",                    "于洋",                   "2015-09", 
   "R语言数据分析与挖掘实战",                 "张良均",                  "2015-10", 
   "R高性能编程:用整套解决方案与高超技巧突破性能瓶颈",    "Aloysius Lim",         "2015-12", 
   "量化投资:以R语言为工具",                 "蔡立耑",                  "2016-01", 
   "R语言初学指南",                      "Brian Dennis",         "2016-01", 
   "应用回归及分类:基于R",                  "吴喜之",                  "2016-01", 
   "R语言实战:编程基础、统计分析与数据挖掘宝典",       "李倩星",                  "2016-03", 
   "投资学及其R语言应用",                   "朱顺泉",                  "2016-03", 
   "基于R语言的自动数据收集",                 "西蒙·蒙策尔特",              "2016-03", 
   "数据科学:理论、方法与R语言实践",             "尼娜·朱梅尔",               "2016-03", 
   "R数据分析秘笈",                      "Viswa Viswanathan",    "2016-03", 
   "R语言数据挖掘方法及应用",                 "薛薇",                   "2016-04", 
   "R语言实战:机器学习与数据分析",              "左飞",                   "2016-05", 
   "R语言在商务分析中的应用",                 "A. 奥赫里",               "2016-06", 
   "R语言与数据挖掘",                     "张良均",                  "2016-06", 
   "网络数据的统计分析:R语言实践",              "Eric D. Kolaczyk",     "2016-06", 
   "R语言入门与实践",                     "Garrett Grolemund",    "2016-06", 
   "预测分析中的建模技术:商务问题与R语言解决方案",      "Thomas W. Miller",     "2016-07", 
   "试验设计与数据分析:基于R语言应用",            "郑杰",                   "2016-08", 
   "多元时间序列分析及金融应用:R语言",            "蔡瑞胸",                  "2016-08", 
   "数据科学实践手册:R+Python",            "Tony Ojeda",           "2016-08", 
   "统计学导论:基于R语言",                  "李勇",                   "2016-09", 
   "R语言预测实战",                      "游皓麟",                  "2016-10", 
   "R语言市场研究分析",                    "克里斯·查普曼",              "2016-10", 
   "数据科学:R语言实战",                   "Dan Toomey",           "2016-11", 
   "R语言与数据分析实战",                   "徐珉久",                  "2017-01", 
   "R语言统计学基础",                     "吕小康",                  "2017-02", 
   "量化金融R语言高级教程",                  "Edina Berlinger",      "2017-05", 
   "量化金融R语言初级教程",                  "Gergely Daroczi",      "2017-05", 
   "深度学习与R语言",                     "程显毅",                  "2017-06", 
   "数据科学:R语言实现",                   "丘祐玮",                  "2017-06", 
   "数据科学R语言实践:面向计算推理与问题求解的案例研究法",  "德博拉·诺兰",               "2017-06", 
   "机器学习与数据科学:基于R的统计学习方法",         "Daniel D. Gutierrez",  "2017-06", 
   "R语言可以很简单",                     "Andrie de Vries",      "2017-07", 
   "R语言游戏数据分析与挖掘",                 "谢佳标",                  "2017-07", 
   "应用回归分析:R语言版",                  "何晓群",                  "2017-07", 
   "数学建模:基于R",                     "薛毅",                   "2017-07", 
   "自动化交易R语言实战指南",                 "Chris Conlan",         "2017-08", 
   "R语言数据分析项目精解:理论、方法、实战",         "罗荣锦",                  "2017-08", 
   "基于R语言的证券公司信用风险计量和管理",          "崔玉征",                  "2017-08", 
   "大数据分析师权威教程:机器学习、大数据分析和可视化",    "Wrox国际IT认证项目",         "2017-08", 
   "深度学习精要:基于R语言",                 "Joshua F. Wiley",      "2017-09", 
   "R语言与大数据编程实战",                  "李倩星",                  "2017-09", 
   "风险模型:基于R的保险损失预测",              "孟生旺",                  "2017-09", 
   "R语言编程指南",                      "任坤",                   "2017-10", 
   "R语言机器学习/第2版",                  "Brett Lantz",          "2017-11", 
   "应用统计分析与R语言实战",                 "吕书龙",                  "2017-11", 
   "基于R语言数据挖掘的统计与分析",              "韦鹏程",                  "2017-12", 
   "数据挖掘与R语言",                     "易正俊",                  "2018-01", 
   "R语言与网络舆情处理",                   "于卫红",                  "2018-01", 
   "R的极客理想:量化投资篇",                 "张丹",                   "2018-01", 
   "概率图模型:基于R语言",                  "大卫·贝洛特",               "2018-01", 
   "R语言商业分析实战",                    "Umesh R. Hodeghatta",  "2018-02", 
   "R语言与医学统计图形",                   "张铁军",                  "2018-02", 
   "文本挖掘:基于R语言的整洁工具",              "Julia Silge",          "2018-03", 
   "R语言统计分析与应用",                   "汪海波",                  "2018-04", 
   "机器学习实践指南:基于R语言",               "尼格尔·刘易斯",              "2018-04", 
   "R语言:大数据分析中的统计方法及应用",           "薛薇",                   "2018-07", 
   "R语言基础与数据科学应用",                 "沈刚",                   "2018-07", 
   "探寻数据背后的逻辑:R语言数据挖掘之道",          "宋云生",                  "2018-08", 
   "R数据科学",                        "哈德利·威克姆",              "2018-08", 
   "大数据分析与算法",                     "拉金德拉·阿卡拉卡",            "2018-10", 
   "数据挖掘与应用:以SAS和R为工具.第2版",        "张俊妮",                  "2018-10", 
   "ggplot2: 数据分析与图形艺术",           "哈德利·威克汉姆",             "2018-11", 
   "数据挖掘算法与R语言实现",                 "肖海军",                  "2018-11", 
   "R语言编程基础",                      "林智章",                  "2019-01", 
   "数据科学实战手册",                     "普拉罕",                  "2019-01", 
   "R语言程序设计基础",                    "文必龙",                  "2019-04", 
   "R语言之书:编程与统计",                  "蒂尔曼·M. 戴维斯",           "2019-05", 
   "R语言数据可视化之美",                   "张杰",                   "2019-05", 
   "R大数据分析实用指南",                   "西蒙·沃克威克",              "2019-05", 
   "R语言数据分析与挖掘实战手册",               "程静",                   "2019-06", 
   "统计分析:以R与Excel为分析工具",           "康拉德·卡尔伯格",             "2019-06", 
   "深度学习企业实战:基于R语言",               "尼格尔·刘易斯",              "2019-06", 
   "R统计数据清洗及应用",                   "马克·范德鲁",               "2019-06", 
   "R数据科学实战:工具详解与案例分析",            "刘健",                   "2019-07", 
   "R语言数据高效处理指南",                  "黄天元",                  "2019-09", 
   "R数据加工与分析呈现宝典",                 "乔纳森·卡罗尔",              "2019-09", 
   "基于R的语言学统计方法",                  "王家钺",                  "2019-10", 
   "现代生物学数据分析原理与应用",               "梅步俊",                  "2019-11", 
   "R语言:实用数据分析和可视化技术",             "贾里德·P. 兰德",            "2020-01", 
   "R语言机器学习",                      "卡西克·拉玛苏布兰马尼安",         "2020-01", 
   "多元统计分析及R语言建模.第5版",             "王斌会",                  "2020-01", 
   "通过实例学习R",                      "吉姆·艾伯特",               "2020-01", 
   "深度学习实战手册:R语言版",                "普拉卡什",                 "2020-01", 
   "R语言统计分析与机器学习",                 "薛震",                   "2020-02", 
   "基于R的数理统计学",                    "崔玉杰",                  "2020-04", 
   "多元统计分析:基于R.第2版",               "费宇",                   "2020-04", 
   "数量生态学:R语言的应用.第2版",             "Daniel Borcard",       "2020-05", 
   "谁说菜鸟不会数据分析,R语言篇",              "方小敏",                  "2020-06", 
   "R语言经典实例",                      "J.D. Long",            "2020-06", 
   "数据可视化:基于R语言",                  "贾俊平",                  "2020-06", 
   "计量经济学实验:基于R语言的实现",             "时奇",                   "2020-06", 
   "R统计编程入门",                      "W. John Braun",        "2020-06", 
   "时间序列分析:基于R.第2版",               "王燕",                   "2020-06", 
   "概率论与数理统计:基于R语言",               "方红",                   "2020-07", 
   "统计学:基于R语言的实现.第3版",             "王涛",                   "2020-07", 
   "R统计高级编程和数据模型:分析、机器学习和可视化",     "马特·威利",                "2020-07", 
   "大规模数据分析和建模:基于Spark与R",         "Javier Luraschi",      "2020-07", 
   "高级R语言编程指南",                    "哈德利·威克汉姆",             "2020-08", 
   "大数据分析:基于R语言",                  "塞玛·阿查亚",               "2020-08", 
   "时间序列分析及其应用:基于R语言实例",           "罗伯特·H.沙姆韦",            "2020-08", 
   "数据分析:基于R语言",                   "潘文超",                  "2020-09", 
   "R语言数据分析与可视化从入门到精通",            "程乾",                   "2020-10", 
   "现代回归分析方法引论",                   "翁洋",                   "2020-10", 
   "R语言数据可视化实战",                   "米霖",                   "2020-11", 
   "机器学习及R应用",                     "陈强",                   "2020-11", 
   "科研数据分析与绘图指导",                  "袁吉有",                  "2020-11", 
   "R语言开发技术标准教程",                  "谢书良",                  "2020-12", 
   "R绘图系统.第3版",                    "保罗·莫雷尔",               "2020-12", 
   "R语言数据分析、挖掘建模与可视化",             "刘顺祥",                  "2021-01", 
   "数据挖掘:基于R语言的实战",                "张俊妮",                  "2021-01", 
   "统计学:基于R.第4版",                  "贾俊平",                  "2021-01", 
   "数据预处理从入门到实战:基于SQL、R、Python",   "本桥智光",                 "2021-02", 
   "大数据生态学研究方法",                   "刘方邻",                  "2021-03", 
   "多元统计分析实验",                     "徐芳燕",                  "2021-03", 
   "文本数据挖掘:基于R语言",                 "黄天元",                  "2021-04", 
   "生物统计学实验指导:SPSS 22.0及R语言应用",    "陈玉华",                  "2021-05", 
   "数据可视化分析:基于R语言.第2版",            "贾俊平",                  "2021-05", 
   "机器学习与R语言",                     "Brett Lantz",          "2021-06", 
   "玩转大数据:SAS+R+Stata+Python",     "孙江伟",                  "2021-06", 
   "统计建模技术I,多元统计建模与时间序列建模",        "罗良清",                  "2021-06", 
   "统计分析:以R语言为工具",                 "朱雪宁",                  "2021-08", 
   "R语言数据分析与可视化",                  "杨剑锋",                  "2022-01", 
   "现代数据科学",                 "本杰明",                  "2022-03",
  "社会科学中的数据分析:R语言的应用", "李泉", "2022-01",
  "R语言在生物统计中的应用", "杨泽峰", "2022-02"
)
df
df= df %>% 
  arrange(desc(Pub_Date)) %>% 
  mutate(ID= 1:n(), .before = Name)
```



```{r echo= FALSE}
knitr::kable(df)
```



# R书籍出版数量



```{r}
df %>% 
  group_by(yr= str_extract(Pub_Date, "\\d{4}")) %>% 
  summarise(n= n()) %>% 
  
  ggplot(aes(yr, n))+
  
  geom_line(aes(group= 1), size= 1)+
  geom_point(size= 4, color= "#e76562")+
  
  theme_light()
```





