---
title: Convert ppm to respiration
author: ''
date: '2023-02-14'
categories: []
slug: flux-calc
tags:
  - ecology
description: ''
keywords: []
link: ''
math: true

output:
  blogdown::html_page:
    toc: true
    number_sections: true

---

更新于2025年3月28日


# 浓度变化速率

## 啊啊

### 啊啊啊


ppm定义：**一百万体积**的空气中所含气体的体积数（体积浓度表示法）

通常公式中最常见的项$\frac{dc}{dt}$，即浓度变化速率。直白地，其单位为$ppm\ h^{-1}$。根据ppm定义，其可以改写为$\mu mol\  mol^{-1}\ h^{-1}$，即单位时间每摩尔的空气中，目标气体浓度变化了多少微摩尔。

a a

# 气体密度

首先计算培养瓶的气体密度

$$PV = nRT$$

标况下，有：

$$P_0V_m = RT_0$$


各项单位分别为

- P，kPa；标准大气压为101.325
- V，L；标况下，气体摩尔体积为22.4
- n，mol  
- T，K；273.15



$$\rho = \frac{n}{V} = \frac{P}{RT} (mol \cdot L)$$
根据以上，气体密度随压强和温度而变，但往往都忽略压强的变化，所以这里也做简化，将P当作P0看待。

则有：

$$\rho = \frac{n}{V} = \frac{\frac{RT_0}{V_m}}{RT} = \frac{T_0}{22.4\times T}$$

上述计算培养瓶顶空气体密度，将其乘以顶空体积V(L)，得到顶空气体摩尔数


$$n = \rho V = \frac{T_0 V}{22.4\times T}$$
dc单位为ppm，等价为$(\mu mol \cdot mol^{-1})$



刚进实验室那会儿为了解决这个问题就费了一番周折，跟师姐。我以为我搞懂了。我觉得是一个非常重要的问题，理解却捉襟见肘，经不起细究。

在草纸上重复写着分式和推导过程，写了一天。更困惑了


和姜师兄讨论用另一条思路讲的，虽然讲的磕磕绊绊，但明显更容易理解。第一条思路绕来绕去，实在看不下去了，一点都不简洁和顺畅。

哈尔滨的妖风，和兴路的拥堵，还有让楠姐期待的“有滋有味小菜馆”……


终于理出了思路，终于解决了。


## 土壤呼吸速率的计算



[ppm单位换算_ppm换算成mg/m3](http://www.szwandi.cn/news/2638)


**经仪器测得，时间段t内CO~2~的浓度增加了a ppm。培养瓶的顶空体积为V (mL)，培养的样品质量为m。如何计算这段时间的土壤呼吸速率？**


体积浓度表示法：**一百万体积**的空气中所含气体的体积数，即ppm；那么：

$$C = 1 \ ppm = \frac{1}{10^6}  = \frac{1cm^3}{1m^3} = \frac{1\ \mu\text{L}}{1\ \text{L}} = \frac{10^{-6}\ \text{mL}}{1\ \text{mL}}$$

以上，1ppm，即$10^{-6}$mL/mL指代的是：单位体积（1mL）中的气体体积为$10^{-6}$mL。



1. 假设培养后气体浓度变化了**a (ppm)**，培养瓶顶空的体积为$V$ (mL)，那么在这段时间，**培养瓶中气体体积改变了多少？**：

$$\Delta V = \Delta C \times V =  a \ ppm \times V = 10^{-6}aV \  (\text{mL})$$


2. 由于$n = \frac{V}{V_m} = \frac{V}{22.4}$， 可计算出**培养瓶中气体，物质的量变化了：**

$$n = \frac{\Delta V }{22.4} = \frac{\Delta C \times V }{22.4} = \frac{a \ ppm \times V }{22.4} = \frac{10^{-6}a V \ (\text{mL})}{22.4\ (\text{L/mol})}\left[\text{m mol}\right]$$

3. 物质的量乘以摩尔质量，可得到**培养瓶中气体质量的变化：**

$$m = n \times M = \frac{\Delta V}{22.4}\times M =   \frac{\Delta C \times V \times M}{22.4} = \frac{10^{-6} aVM}{22.4}(\text{mg})$$


4. **最后计算单位时间、单位土壤，土壤呼吸排出了多少质量的气体？**，其中培养时间单位h，土样质量单位g。

$$R_s\ (\text{mg g soil}^{-1}\ \text{h}^{-1}) = \frac{m}{t \times m_\text{soil} } = \frac{n \times M}{t \times m_\text{soil}}  = \frac{10^{-6} \times \Delta C\times V \times M}{22.4 \times t \times m_\text{soil}}  = \frac{1}{10^6}\frac{\Delta C}{t} \frac{V}{22.4} \frac{M}{m_\text{soil}}$$



