---
title: Canon R6 Settings
author: Xue Kui
date: '2023-01-09'
slug: r6-settings
categories: []
tags:
  - 星空摄影
description: ''
keywords: []
link: ''
---


## 按键操作

1. 先调整屈光度。确保在取景器中看到的是清晰的

1. 导出/删除照片  
把SD卡的照片传到（复制到）电脑，然后弹出  
如果照片不用了，在相机里面进行**格式化**，（不在电脑上删除，只用电脑来拷贝）

1. 镜头对焦环问题  
一般是自动对焦。我也不太清楚自动对焦模式下，手动去拧镜头上的对焦环会不会出问题。



1. 查看相册：

- 滚动转盘来切换图像，很方便
- 按`r emo::ji("mag")`键放大照片，然后可以摁`r emo::ji("mag")`左上角的那个键（**方向键**），上下左右移动照片。
- **触摸屏幕缩放照片**也很好用。

---

5. Q键，能调整哪些？

- 自动对焦方式
  - **默认是眼部追焦**，拍人像确实好用啊
  - 拍静物的时候，可以换成单点对焦，或者扩展自动对焦区域
- 驱动模式：高速、低速连拍
- 测光模式：默认的评价测光就可以

---

6. **三个拨盘分别可以调整ISO、快门、光圈数值**

- 一般ISO设成自动，但尽量低于6400，控制画面噪点
- 快门一般是几百分之一，100分之一~500分之一，也就是快门释放要快一点；如果快门是1s，很有可能是糊的；不过EOS R6有机身防抖，拍出来应该会好点。
- 光圈：晚上或室内光线弱，需要用大一点的光圈，最大光圈是F1.8；白天室外的话，用小一点的光圈，F4~F8；（大光圈虚化效果好）


或者调整**模式转盘**，用到比较多的模式是：

>- M，手动模式，手动调整光圈和快门；
>- Av，光圈优先，光圈是固定的（个人设置的）；然后机身会自动调整快门速度，以获得正常曝光
>- Tv，快门优先，也就是快门速度不变；机身会自动改变光圈大小，获得正常曝光



7. 一次一次按INFO键，可以调整屏幕的显示信息



<br>




# 相机的菜单，我设置/调整了哪些内容？


## 拍摄菜单

图像画质：保存RAW格式

- 此时JPEG格式为：—，即不保存JPEG
- 如果想直出JPEG，（保存RAW和JPEG），选择第一个L就可以
- L M S 分别代表画质：Large, Middle, Small


图像确认

- 默认是2s，拍完的照片会在屏幕上停留2s；
- 但这个影响连续摁快门，我给关了（确认时长：关）








## AF自动对焦菜单


触摸和拖拽自动对焦设置

- 非常好用。快速调整**对焦点**。用取景器拍摄时，同时用左手食指在屏幕（左侧区域）触摸可以移动对焦点
- 已设置为：启用；相对；左


也可以**直接触屏对焦**；或者摁方向键来调整对焦点的位置（第84页）





## 设置菜单（小扳手图标）

文件编号：连续。自动旋转：开+Camera+PC

屏幕/取景器显示：AUOTO1

屏幕亮度：3（默认是4）



节电

- 显示屏关闭：15s
- 自动关闭电源：1min
- 取景器关闭：3min

## 自定义功能菜单（第二个相机图标）

未装镜头释放快门：ON







